spring:
  profiles:
    active: dev

---
server:
  max-http-header-size: 8192
  port: 8888
spring:
  application:
    name: demo

  redis:
    database: 0
    host: localhost
    port: 6379
  session:
    store-type: redis
    timeout: 600s


